baseurl = "https://ankdesh.github.io/"
languageCode = "en-us"
title = "Ankdesh's Blog site"
theme = "hugo-theme-learn"
publishdir = "public"
Author = "Ankur Deshwal"
disqusShortname = "ankdesh"

[original]
  name = "Ankdesh"
  homepage = "https://ankdesh.github.io"
  repo = "https://github.com/ankdesh"

